version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: postgresql
    volumes:
      - ./postgres-volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scrapper
    ports:
      - "5432:5432"
    networks:
      - backend
  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
networks:
  backend:
    driver: bridge